name: Test

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          auto-activate-base: false
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install python=3.11 pytest coverage numpy numba
      - name : Display packages
        run: |
          numba -s
      - name: Install numba-pixie with pip
        shell: bash -l {0}
        run: |
          python -m pip install -vv -e .
      - name: Run pytest and print coverage Report
        shell: bash -l {0}
        run: |
          coverage run -m pytest --pyargs pixie
          coverage report
